
package netflix;

import java.awt.Color;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author pc
 */
public class KayitSayfasi extends javax.swing.JFrame {

    /**
     * Creates new form KayitSayfasi
     */
    public KayitSayfasi() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        kayitarkaplan = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        OturumAcYazisi = new javax.swing.JLabel();
        MailAdresi = new javax.swing.JLabel();
        MailAdresi1 = new javax.swing.JLabel();
        MailAdresi2 = new javax.swing.JLabel();
        MailAdresi3 = new javax.swing.JLabel();
        MailAdresi4 = new javax.swing.JLabel();
        AdKayit = new javax.swing.JTextField();
        MailKayit = new javax.swing.JTextField();
        KayitOlButonu = new javax.swing.JButton();
        SifreKayit = new javax.swing.JPasswordField();
        SifreTekrar = new javax.swing.JPasswordField();
        DogumTarihiKayit = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        komedi = new javax.swing.JCheckBox();
        aksiyon = new javax.swing.JCheckBox();
        drama = new javax.swing.JCheckBox();
        romantizm = new javax.swing.JCheckBox();
        gerilim = new javax.swing.JCheckBox();
        korku = new javax.swing.JCheckBox();
        bilimkurgu = new javax.swing.JCheckBox();
        bilimdoga = new javax.swing.JCheckBox();
        cocuk = new javax.swing.JCheckBox();
        belgesel = new javax.swing.JCheckBox();
        SifreGiris = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        kayitarkaplan.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/netflix.PNG"))); // NOI18N

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        OturumAcYazisi.setBackground(new java.awt.Color(204, 0, 0));
        OturumAcYazisi.setFont(new java.awt.Font("Bauhaus 93", 0, 18)); // NOI18N
        OturumAcYazisi.setForeground(new java.awt.Color(255, 0, 0));
        OturumAcYazisi.setText("KAYIT OL");

        MailAdresi.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        MailAdresi.setForeground(new java.awt.Color(255, 0, 0));
        MailAdresi.setText("ŞİFRE TEKRARI:");

        MailAdresi1.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        MailAdresi1.setForeground(new java.awt.Color(255, 0, 0));
        MailAdresi1.setText("ŞİFRE:");

        MailAdresi2.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        MailAdresi2.setForeground(new java.awt.Color(255, 0, 0));
        MailAdresi2.setText("AD:");

        MailAdresi3.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        MailAdresi3.setForeground(new java.awt.Color(255, 0, 0));
        MailAdresi3.setText("DOGUM TARİHİ:");

        MailAdresi4.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        MailAdresi4.setForeground(new java.awt.Color(255, 0, 0));
        MailAdresi4.setText("MAIL ADRESİ:");

        KayitOlButonu.setBackground(new java.awt.Color(255, 0, 0));
        KayitOlButonu.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        KayitOlButonu.setText("KAYIT OL");
        KayitOlButonu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KayitOlButonuActionPerformed(evt);
            }
        });

        DogumTarihiKayit.setForeground(new java.awt.Color(153, 153, 153));
        DogumTarihiKayit.setText("GG/AA/YYYY");
        DogumTarihiKayit.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                DogumTarihiKayitFocusGained(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 0, 0));
        jLabel2.setText("Aşağıdaki türlerden hangilerini izlemeyi daha çok seversiniz?(3 tane seçiniz.)");

        komedi.setBackground(new java.awt.Color(255, 255, 255));
        komedi.setForeground(new java.awt.Color(255, 0, 0));
        komedi.setText("Komedi");

        aksiyon.setBackground(new java.awt.Color(255, 255, 255));
        aksiyon.setForeground(new java.awt.Color(255, 0, 0));
        aksiyon.setText("Aksiyon");

        drama.setBackground(new java.awt.Color(255, 255, 255));
        drama.setForeground(new java.awt.Color(255, 0, 0));
        drama.setText("Dramalar");

        romantizm.setBackground(new java.awt.Color(255, 255, 255));
        romantizm.setForeground(new java.awt.Color(255, 0, 0));
        romantizm.setText("Romantizm");

        gerilim.setBackground(new java.awt.Color(255, 255, 255));
        gerilim.setForeground(new java.awt.Color(255, 0, 0));
        gerilim.setText("Gerilim");

        korku.setBackground(new java.awt.Color(255, 255, 255));
        korku.setForeground(new java.awt.Color(255, 0, 0));
        korku.setText("Korku");

        bilimkurgu.setBackground(new java.awt.Color(255, 255, 255));
        bilimkurgu.setForeground(new java.awt.Color(255, 0, 0));
        bilimkurgu.setText("Bilim Kurgu ve Fantastik Yapımlar");

        bilimdoga.setBackground(new java.awt.Color(255, 255, 255));
        bilimdoga.setForeground(new java.awt.Color(255, 0, 0));
        bilimdoga.setText("Bilim ve Doga");

        cocuk.setBackground(new java.awt.Color(255, 255, 255));
        cocuk.setForeground(new java.awt.Color(255, 0, 0));
        cocuk.setText("Çocuk ve Aile");

        belgesel.setBackground(new java.awt.Color(255, 255, 255));
        belgesel.setForeground(new java.awt.Color(255, 0, 0));
        belgesel.setText("Belgesel");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(OturumAcYazisi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(229, 229, 229))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(MailAdresi2)
                        .addGap(93, 93, 93))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(MailAdresi4)
                                    .addComponent(MailAdresi1))
                                .addGap(31, 31, 31))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(MailAdresi3)
                                .addGap(18, 18, 18)))))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(AdKayit)
                    .addComponent(MailKayit, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(SifreKayit)
                    .addComponent(DogumTarihiKayit))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(MailAdresi)
                .addGap(26, 26, 26)
                .addComponent(SifreTekrar)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(komedi)
                                .addGap(77, 77, 77)
                                .addComponent(romantizm))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(drama)
                                    .addComponent(aksiyon))
                                .addGap(67, 67, 67)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(korku)
                                    .addComponent(gerilim)))
                            .addComponent(bilimkurgu))
                        .addGap(68, 68, 68)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cocuk)
                            .addComponent(bilimdoga)
                            .addComponent(belgesel))))
                .addContainerGap(74, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(KayitOlButonu)
                .addGap(221, 221, 221))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(OturumAcYazisi, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(MailAdresi2, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(AdKayit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(MailAdresi3, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(DogumTarihiKayit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(17, 17, 17)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(MailAdresi4, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(MailKayit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(SifreKayit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(MailAdresi1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(SifreTekrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(MailAdresi, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(romantizm)
                            .addComponent(bilimdoga)
                            .addComponent(komedi))
                        .addGap(6, 6, 6)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(aksiyon)
                            .addComponent(cocuk))
                        .addGap(18, 18, 18)
                        .addComponent(belgesel))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(gerilim)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(drama)
                            .addComponent(korku))))
                .addGap(18, 18, 18)
                .addComponent(bilimkurgu)
                .addGap(18, 18, 18)
                .addComponent(KayitOlButonu, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39))
        );

        javax.swing.GroupLayout kayitarkaplanLayout = new javax.swing.GroupLayout(kayitarkaplan);
        kayitarkaplan.setLayout(kayitarkaplanLayout);
        kayitarkaplanLayout.setHorizontalGroup(
            kayitarkaplanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kayitarkaplanLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(373, 373, 373)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(485, Short.MAX_VALUE))
            .addGroup(kayitarkaplanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(kayitarkaplanLayout.createSequentialGroup()
                    .addGap(682, 682, 682)
                    .addComponent(SifreGiris)
                    .addGap(682, 682, 682)))
        );
        kayitarkaplanLayout.setVerticalGroup(
            kayitarkaplanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kayitarkaplanLayout.createSequentialGroup()
                .addGroup(kayitarkaplanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(kayitarkaplanLayout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jLabel1))
                    .addGroup(kayitarkaplanLayout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(334, Short.MAX_VALUE))
            .addGroup(kayitarkaplanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(kayitarkaplanLayout.createSequentialGroup()
                    .addGap(434, 434, 434)
                    .addComponent(SifreGiris, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(434, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(kayitarkaplan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 141, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(kayitarkaplan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    //mailin kayitli olup olmadigini kontrol eder. 
    public boolean mailkontrol(String mail)
    {
        PreparedStatement ps = null;
        ResultSet rs = null;
        boolean kontrol = false;
        String query = "SELECT * FROM `kullanici` WHERE `email` =?";
        
        try {
            ps = Baglanti.Bagla().prepareStatement(query);
            ps.setString(1, mail);
            
            rs = ps.executeQuery();
            
            if(rs.next())
            {
                kontrol = true;
            }
        } catch (SQLException ex) {
            Logger.getLogger(KayitSayfasi.class.getName()).log(Level.SEVERE, null, ex);
        }finally{
            try {
                ps.close();
                rs.close();
            } catch (Exception ex) {
               
            }
            
        }
         return kontrol;
    }
    private void KayitOlButonuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KayitOlButonuActionPerformed
        String isim = AdKayit.getText();
        String dogum_tarihi = DogumTarihiKayit.getText();
        String mail = MailKayit.getText();
        String sifre = String.valueOf(SifreKayit.getPassword());
        String sifre_tekrar = String.valueOf(SifreTekrar.getPassword());
        
        if(isim.equals(""))
        {
            JOptionPane.showMessageDialog(null, "ADINIZI GIRINIZ!");
        }
        
        else if(sifre.equals(""))
        {
            JOptionPane.showMessageDialog(null, "SIFRENIZI GIRINIZ!");
        }
        else if(!sifre.equals(sifre_tekrar))
        {
            JOptionPane.showMessageDialog(null, "SIFRELER ESLESMİYOR!");
        }
         else if(mailkontrol(mail))
        {
            JOptionPane.showMessageDialog(null, "BU MAIL ADRESI ZATEN KULLANIMDA!");
        }
         else{
           
        PreparedStatement ps;
        String query = "INSERT INTO `kullanici`( `email`, `sifre`, `dogum_tarihi`, `kullanici_ad`) VALUES (?,?,?,?)";
        
        try {
            ps = Baglanti.Bagla().prepareStatement(query);
            
            ps.setString(1, mail);
            ps.setString(2, sifre);
            ps.setString(3, dogum_tarihi);
            ps.setString(4, isim);
            
            
            if(ps.executeUpdate() > 0)
            {
                //JOptionPane.showMessageDialog(null, "KULLANICI EKLENDI!");
                AnaSayfa as = new AnaSayfa();
                as.setVisible(true);
            }
            
        } catch (SQLException ex) {
            Logger.getLogger(KayitSayfasi.class.getName()).log(Level.SEVERE, null, ex);
        }
        }
    }//GEN-LAST:event_KayitOlButonuActionPerformed

    private void DogumTarihiKayitFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_DogumTarihiKayitFocusGained
        if(DogumTarihiKayit.getText().trim().equals("GG/AA/YYYY"))
        {
            DogumTarihiKayit.setText("");
            DogumTarihiKayit.setForeground(Color.black);
        }
    }//GEN-LAST:event_DogumTarihiKayitFocusGained
     public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(KayitSayfasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(KayitSayfasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(KayitSayfasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(KayitSayfasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new KayitSayfasi().setVisible(true);
            }
        });
    }
    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField AdKayit;
    private javax.swing.JTextField DogumTarihiKayit;
    private javax.swing.JButton KayitOlButonu;
    private javax.swing.JLabel MailAdresi;
    private javax.swing.JLabel MailAdresi1;
    private javax.swing.JLabel MailAdresi2;
    private javax.swing.JLabel MailAdresi3;
    private javax.swing.JLabel MailAdresi4;
    private javax.swing.JTextField MailKayit;
    private javax.swing.JLabel OturumAcYazisi;
    private javax.swing.JPasswordField SifreGiris;
    private javax.swing.JPasswordField SifreKayit;
    private javax.swing.JPasswordField SifreTekrar;
    private javax.swing.JCheckBox aksiyon;
    private javax.swing.JCheckBox belgesel;
    private javax.swing.JCheckBox bilimdoga;
    private javax.swing.JCheckBox bilimkurgu;
    private javax.swing.JCheckBox cocuk;
    private javax.swing.JCheckBox drama;
    private javax.swing.JCheckBox gerilim;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel kayitarkaplan;
    private javax.swing.JCheckBox komedi;
    private javax.swing.JCheckBox korku;
    private javax.swing.JCheckBox romantizm;
    // End of variables declaration//GEN-END:variables
}
